#!/bin/bash

echo "* Starting wallet RPC 1..."
/usr/bin/bittube-wallet-rpc --rpc-bind-port 29082 --daemon-port 29081 --testnet --wallet-file /data/wallet-1/wallet.bin --rpc-bind-ip 0.0.0.0 --confirm-external-bind --rpc-login monerorpc:rpcpassword --password ""
