#!/bin/bash

echo "* Starting wallet RPC 2..."
/usr/bin/bittube-wallet-rpc --rpc-bind-port 39082 --daemon-port 39081 --testnet --wallet-file /data/wallet-2/wallet.bin --rpc-bind-ip 0.0.0.0 --confirm-external-bind --rpc-login monerorpc:rpcpassword --password ""